//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.EMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int eventId { get; set; }
        public string @event { get; set; }
        public Nullable<int> eventTypeId { get; set; }
        public string cfgItmId { get; set; }
        public string userName { get; set; }
        public string accGrpId { get; set; }
    }
}
