//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.CMDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CMDBEntities : DbContext
    {
        public CMDBEntities()
            : base("name=CMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAppGrp> tblAppGrp { get; set; }
        public virtual DbSet<tblAppStruct> tblAppStruct { get; set; }
        public virtual DbSet<tblAppStructTyp> tblAppStructTyp { get; set; }
        public virtual DbSet<tblCfgItm> tblCfgItm { get; set; }
        public virtual DbSet<tblCfgItmAtb> tblCfgItmAtb { get; set; }
        public virtual DbSet<tblCfgItmTypAtb> tblCfgItmTypAtb { get; set; }
        public virtual DbSet<tblApp> tblApp { get; set; }
        public virtual DbSet<vw_Menu> vw_Menu { get; set; }
    
        public virtual ObjectResult<sp_WorkFlow_Result> sp_WorkFlow(Nullable<int> appId, Nullable<int> grpId)
        {
            var appIdParameter = appId.HasValue ?
                new ObjectParameter("AppId", appId) :
                new ObjectParameter("AppId", typeof(int));
    
            var grpIdParameter = grpId.HasValue ?
                new ObjectParameter("GrpId", grpId) :
                new ObjectParameter("GrpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_WorkFlow_Result>("sp_WorkFlow", appIdParameter, grpIdParameter);
        }
    }
}
