//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.CMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCfgItm
    {
        public string cfgItmId { get; set; }
        public string cfgItm { get; set; }
        public string parentCfgItmId { get; set; }
    }
}
