//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.CMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Menu
    {
        public string appStructId { get; set; }
        public Nullable<int> appId { get; set; }
        public string appStructTypId { get; set; }
        public string appStructTyp { get; set; }
        public Nullable<int> parentAppStructId { get; set; }
        public string appStructVal { get; set; }
    }
}
