//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.UAMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWf
    {
        public string wfId { get; set; }
        public string wfName { get; set; }
        public Nullable<bool> isAccGrpOrgWf { get; set; }
    }
}
