//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.UAMDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UAMDBEntities : DbContext
    {
        public UAMDBEntities()
            : base("name=UAMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccGrp> tblAccGrp { get; set; }
        public virtual DbSet<tblCfgItm> tblCfgItm { get; set; }
        public virtual DbSet<tblLinkEmp> tblLinkEmp { get; set; }
        public virtual DbSet<tblUsr> tblUsr { get; set; }
        public virtual DbSet<tblWf> tblWf { get; set; }
        public virtual DbSet<tblWfStatus> tblWfStatus { get; set; }
        public virtual DbSet<tblWfStep> tblWfStep { get; set; }
        public virtual DbSet<tblWfStepAccGrp> tblWfStepAccGrp { get; set; }
        public virtual DbSet<tblWfStepTrx> tblWfStepTrx { get; set; }
        public virtual DbSet<AccGrp> AccGrp { get; set; }
        public virtual DbSet<AccessModule> AccessModule { get; set; }
        public virtual DbSet<WorkFlow> WorkFlow { get; set; }
        public virtual DbSet<AuthAudit> AuthAudit { get; set; }
    
        public virtual ObjectResult<string> sp_Authenticate(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Authenticate", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_GetAppComponents_Result> sp_GetAppComponents(string grpName, Nullable<int> appParent)
        {
            var grpNameParameter = grpName != null ?
                new ObjectParameter("GrpName", grpName) :
                new ObjectParameter("GrpName", typeof(string));
    
            var appParentParameter = appParent.HasValue ?
                new ObjectParameter("AppParent", appParent) :
                new ObjectParameter("AppParent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAppComponents_Result>("sp_GetAppComponents", grpNameParameter, appParentParameter);
        }
    }
}
