//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.EntityFramework.UAMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow
    {
        public int SKU { get; set; }
        public string ProductName { get; set; }
        public string ApprovalStatus { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> ApprovalDptFood { get; set; }
        public Nullable<bool> ApprovalDivBuyer { get; set; }
        public string DataFilter { get; set; }
    }
}
